DROP TABLE IF EXISTS rounds;

CREATE TABLE rounds (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  date BIGINT NOT NULL,
  location TEXT NOT NULL,
  name TEXT NOT NULL,
  strokes INTEGER NOT NULL,
  notes TEXT NOT NULL
);
